### PR TITLE
Add missing `background` prop for `imagesLoaded`

### PR DESCRIPTION
**Pull request by brahma-dev**

### CODE REVIEW

**Comment by oyvindhermansen** [comment]
Hey @brahma-dev ! Thanks for your pull request 👍  I'll take a look in between work hours today, and get back to you with my feedback :)

**Comment by brahma-dev** [comment]
I'll leave that to you. I am fairly new to the react ecosystem.

**Comment by oyvindhermansen** [comment]
@brahma-dev I'm OK with fixing defaultProp myself :) If you could update the branch you want to merge into to `release/v1.1.0`, and I'll prepare for a new release in a few days.

**Comment by oyvindhermansen** [comment]
Thanks, @brahma-dev  for your time and effort. Highly appreciated. I'll merge this, and hopefully it will be released really soon 👍

**Pull request merged**
